apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: administration
commonLabels:
  io.biza/component: admin
  io.biza/system: adr
helmCharts:
  - name: ingress-nginx
    releaseName: admin-ingress
    repo: https://kubernetes.github.io/ingress-nginx
    valuesFile: config/helm-admin-ingress.yaml
    includeCRDs: true
resources:
  - resources/admin-service-account.yaml
  - resources/appliance-admin-definition.yaml
  - resources/ingress-admin-secure.yaml
configMapGenerator:
  - name: admin-app-config
    files:
      - config/default.json
