#!/bin/bash
set -euo pipefail

CERT_MANGER_VERSION=v1.12.0
# To make helm work see https://microk8s.io/docs/services-and-ports
HELM_CMD="helm --kubeconfig /var/snap/microk8s/current/credentials/client.config"

current_directory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
name=$(basename $current_directory)

echo "*** Setup ${name} starting..."

echo "### Ensuring addon dependencies been enabled..."
$SNAP/microk8s-enable.wrapper rbac
$SNAP/microk8s-enable.wrapper hostpath-storage

echo "### Setup certmanager..."
$SNAP/microk8s-kubectl.wrapper apply -f https://github.com/cert-manager/cert-manager/releases/download/${CERT_MANGER_VERSION}/cert-manager.yaml

echo "### Setup base kustomize..."
$SNAP/microk8s-kubectl.wrapper kustomize --enable-helm $current_directory/k8s | $SNAP/microk8s-kubectl.wrapper apply -f -

echo "*** Setup $name complete"
