apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-deployment-role
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces", "pods", "configmaps", "secrets", "services", "apps" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "apps" ]
    resources: [ "ingresses", "deployments" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-deployment-binding
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-deployment-role # name of Role
subjects: # points to the ServiceAccount
  - kind: ServiceAccount
    name: admin-serviceaccount # service account to bind to
