#!/bin/bash
set -e

current_directory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
name=$(basename $current_directory)

echo "*** Are you sure? <ctrl+c> to quit ***
All data in cluster will be effected. Data in s3 will be untouched"
sleep 10
echo "Disabling $name"
find ${current_directory}/kube-prometheus | grep -v namespace | xargs -n 1 $SNAP/microk8s-kubectl.wrapper delete --ignore-not-found=true -f
$SNAP/microk8s-kubectl.wrapper delete --ignore-not-found=true -f ${current_directory}/kube-prometheus/setup/namespace.yaml
$SNAP/microk8s-kubectl.wrapper delete -f ${current_directory}/kube-prometheus/setup/namespace.yaml --ignore-not-found=true
$SNAP/microk8s-kubectl.wrapper delete -f ${current_directory}/kube-thanos --ignore-not-found=true

echo "Disabled $name"

rm ${SNAP_DATA}/var/lock/biza-${name}.lock