#!/bin/bash
set -e

current_directory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
name=$(basename $current_directory)

echo "Enabling dependencies"
$SNAP/microk8s-enable.wrapper storage

echo "Enabling $name"
$SNAP/microk8s-kubectl.wrapper apply -f ${current_directory}/kube-prometheus/setup/namespace.yaml
$SNAP/microk8s-kubectl.wrapper apply -f ${current_directory}/kube-prometheus/setup --server-side
$SNAP/microk8s-kubectl.wrapper apply -f ${current_directory}/kube-prometheus

$SNAP/microk8s-kubectl.wrapper apply -f ${current_directory}/kube-thanos/namespace.yaml
$SNAP/microk8s-kubectl.wrapper apply -f ${current_directory}/kube-thanos

echo "Enabled $name"

touch ${SNAP_DATA}/var/lock/biza-${name}.lock
