#!/bin/bash
set -euo pipefail

CMCTL_VERSION=v1.12.3
CMCTL_FILENAME=cmctl.tar.gz
CERT_MANGER_VERSION=v1.12.0
# To make helm work see https://microk8s.io/docs/services-and-ports
HELM_CMD="helm --kubeconfig /var/snap/microk8s/current/credentials/client.config"

current_directory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
name=$(basename $current_directory)

echo "*** Setup ${name} starting..."

echo "### Ensuring addon dependencies been enabled..."
$SNAP/microk8s-enable.wrapper rbac

echo "### Creating separate ingress controllers..."
for HELM_VALUES_FILE in $(find ${current_directory}/ingress -type f)
do
  INGRESS_TARGET_NAME="$(basename ${HELM_VALUES_FILE} |  cut -d'.' -f1)"
  echo "### Installing ingress ${INGRESS_TARGET_NAME}"
  ${HELM_CMD} upgrade --install ${INGRESS_TARGET_NAME} ingress-nginx \
    --repo https://kubernetes.github.io/ingress-nginx \
    --namespace ingress-nginx --create-namespace -f ${HELM_VALUES_FILE}
done

echo "### Creating separate ingress controllers...Done"

echo "### Setting up cert-manager ${CERT_MANGER_VERSION}"
[ -f ${CMCTL_FILENAME} ] || curl -fsSL -o ${CMCTL_FILENAME} https://github.com/cert-manager/cert-manager/releases/download/${CMCTL_VERSION}/cmctl-linux-amd64.tar.gz
tar xzf cmctl.tar.gz
sudo mv cmctl /usr/local/bin
rm cmctl.tar.gz

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/${CERT_MANGER_VERSION}/cert-manager.yaml
while ! kubectl apply -f ${current_directory}/cert-tester.yaml > /dev/null 2>&1
do
    echo -n "."
    sleep 5
done
echo "ready"
kubectl delete -f ${current_directory}/cert-tester.yaml > /dev/null 2>&1 || true

echo "### Setup kms-issuer..."
${HELM_CMD} upgrade --install kms-issuer kms-issuer \
  --repo 'https://skyscanner.github.io/kms-issuer' --namespace kms-issuer-system \
  --create-namespace -f ${current_directory}/kms-issuer-values.yaml

echo "### Creating certificate signing resources..."
kubectl apply -f ${current_directory}/kms-issuer.yaml
echo "### Creating certificate signing resources... Done"

echo "### Enabling $name"
kubectl apply -k ${current_directory}/admin

echo "*** Setup $name complete"
