apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: administration
commonLabels:
  io.biza/component: admin
  io.biza/system: adr
resources:
  - resources/admin-service-account.yaml
  - resources/og-admin-definition.yaml
  - resources/ingress-admin-secure.yaml
configMapGenerator:
  - name: admin-app-config
    files:
      - config/default.json
  - name: admin-app-deployment-config
    files:
      - config/og-appliance.yml
      - config/nginxdemo.yml
secretGenerator:
  - name: nextauth
    literals:
      - secret=c!4R@K++!4XiswuSlth6qe0hI&8cl4t#w:w:qe$aThL&hE+2oche#uWro&&lnEx_?6U!