#!/bin/bash
set -e

current_directory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
name=$(basename $current_directory)

echo "*** Are you sure? <ctrl+c> to quit ***
All data in cluster will be effected. Data in s3 will be untouched"
sleep 10
echo "Disabling $name"
$SNAP/microk8s-kubectl.wrapper delete namespace vector

echo "Disabled $name"

rm ${SNAP_DATA}/var/lock/biza-${name}.lock