#!/bin/bash
set -e

current_directory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
name=$(basename $current_directory)

echo "Enabling $name"
$SNAP/microk8s-kubectl.wrapper apply -k ${current_directory}/vector-aggregator
$SNAP/microk8s-kubectl.wrapper apply -k ${current_directory}/vector-agent

echo "Enabled $name"

touch ${SNAP_DATA}/var/lock/biza-${name}.lock
