#!/bin/bash
set -euo pipefail

current_directory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
name=$(basename $current_directory)

echo "*** Setup ${name} starting..."

echo "### Ensuring addon dependencies been enabled..."
$SNAP/microk8s-enable.wrapper rbac
$SNAP/microk8s-enable.wrapper core/dashboard

echo "### Done with addon dependencies"

echo "### Enabling dashboard ingress"
$SNAP/microk8s-kubectl.wrapper apply -f ${current_directory}/dashboard.yaml
echo "### Enabled dashboard ingress"

touch ${SNAP_DATA}/var/lock/biza-dashboard-ingress.lock

echo "
### To create a read only token for the dashboard run
kubectl create token admin-readonly-user -n kube-system
### To create a read/write *** CAUTION *** run
kubectl create token admin-user -n kube-system

*** Setup ${name} complete
"